[package]
name = "cwl_core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "CWL Rust library, intended to be used for YAML parsing with serde"
authors.workspace = true
keywords = [
    "cwl",
    "common workflow language",
    "commonwl",
    "workflow",
    "fairagro",
]
categories = ["science"]

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
sha1 = "0.10.6"

[dev-dependencies]
rstest = { workspace = true }
test_utils = { workspace = true }
serial_test = { workspace = true }
