[package]
name = "test_utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
path = "lib.rs"

[dependencies]
git2 = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
copy_dir = "0.1.3"
whoami = "1.6.1"
