[package]
name = "util"
description = "top-level helper functions"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
wait-timeout = "0.2.1"
