[package]
name = "remote_execution"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
reana = { path = "../reana" }
commonwl = { path = "../cwl" }
util = { path = "../util" }
s4n_core = { path = "../core" }
anyhow.workspace = true
colored.workspace = true
dialoguer.workspace = true
keyring.workspace = true
log.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
toml.workspace = true
uuid.workspace = true

[lints]
workspace = true
