[package]
name = "s4n"
description = "SciWIn Client: Reproducible computational Workflows made easy!"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
keywords = ["cwl", "common workflow language", "SciWIn", "workflow", "fairagro"]
categories = ["science"]

[lints]
workspace = true

[dependencies]
s4n_core = { path = "../core" }
repository = { path = "../repository" }
commonwl = { path = "../cwl", features = ["execution", "annotation"] }
remote_execution = { path = "../remote_execution" }
util = { path = "../util" }

anyhow = { workspace = true }
colored = { workspace = true }
dialoguer = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

clap = { version = "4.5.44", features = ["derive", "wrap_help"] }
clap_complete = "4.5.57"
ignore = "0.4.23"
prettytable-rs = "0.10.0"

syntect = { version = "5.2.0", default-features = false, features = [
    "regex-fancy",
    "parsing",
    "default-themes",
    "default-syntaxes",
] }
similar = "2.7.0"

[dev-dependencies]
shlex = "1.3.0"

test_utils = { workspace = true }
serial_test = { workspace = true }
fstest = { workspace = true }
