[package]
name = "s4n"
description = "SciWIn Client: Reproducible computational Workflows made easy!"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
keywords = ["cwl", "common workflow language", "SciWIn", "workflow", "fairagro"]
categories = ["science"]

[lints]
workspace = true

[dependencies]
commonwl = { path = "../cwl", features = ["execution", "annotation"] }
remote_execution = { path = "../remote_execution" }
util = { path = "../util" }

anyhow = { workspace = true }
dialoguer = { workspace = true }
git2 = { workspace = true }
keyring = { workspace = true }
log = { workspace = true }
pathdiff = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
uuid = { workspace = true }

clap = { version = "4.5.44", features = ["derive", "wrap_help"] }
clap_complete = "4.5.57"
colored = "3.0.0"
configparser = "3.1.0"
ignore = "0.4.23"
prettytable-rs = "0.10.0"
rust_xlsxwriter = "0.89.1"
shlex = "1.3.0"
slugify = "0.1.0"
syntect = { version = "5.2.0", default-features = false, features = [
    "regex-fancy",
    "parsing",
    "default-themes",
    "default-syntaxes",
] }
semver = { version = "1.0.26", features = ["serde"] }
smart-default = "0.7.1"
similar = "2.7.0"

[dev-dependencies]
calamine = "0.30.0"
fstest = "0.2.4"
predicates = "3.1.3"

test_utils = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }
