[package]
name = "repository"
description = "A proxy crate for git repository related operations"

version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
git2.workspace = true
anyhow.workspace = true
configparser = "3.1.0"

[dev-dependencies]
fstest = { workspace = true }

[lints]
workspace = true
