[package]
name = "s4n_core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
commonwl = { path = "../cwl", features = ["execution", "annotation"] }
util = { path = "../util" }

anyhow.workspace = true
pathdiff.workspace = true
rand = { workspace = true }
serde_yaml.workspace = true

shlex = "1.3.0"
slugify = "0.1.0"

[dev-dependencies]
test_utils = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }

[lints]
workspace = true
