import { Button, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property <int> counter: 69420;

    callback request-value-increment();

    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increment +1";
            clicked => {
                root.request-value-increment();
            }
        }
    }
}
