name: Draft PDF

on: 
  push: 
    branches: ["paper/joss"]
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf